# Generated by Django 5.0.2 on 2025-05-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='category',
            field=models.CharField(choices=[('enterprise', 'Entreprises'), ('university', 'Universités'), ('hotel', 'Hôtels'), ('sport', 'Sports')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
