# Generated by Django 5.0.2 on 2025-05-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_roomtype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('validated', 'Validée'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
    ]
