# Generated by Django 5.2 on 2025-05-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="Classe Font Awesome pour l'icône", max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='core.equipment'),
        ),
    ]
