from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('preview/', views.preview_site, name='preview_site'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('notifications/', views.notifications, name='notifications'),
    # URLs d'administration personnalisée
    path('manage/rooms/', views.manage_rooms, name='manage_rooms'),
    path('manage/users/', views.manage_users, name='manage_users'),
    path('manage/bookings/', views.manage_bookings, name='manage_bookings'),
    path('room-types/', views.room_types, name='room_types'),
    path('rooms/', views.room_list, name='room_list'),
    path('rooms/<int:pk>/', views.room_detail, name='room_detail'),
    path('rooms/<int:pk>/book/', views.book_room, name='book_room'),
    path('bookings/', views.booking_list, name='booking_list'),
    path('bookings/<int:pk>/payment/', views.payment, name='payment'),
    path('bookings/<int:pk>/cancel/', views.cancel_booking, name='cancel_booking'),
    path('contact/', views.contact, name='contact'),
    path('help/', views.help_page, name='help'),
    path('bookings/', views.my_bookings, name='my_bookings'),
    path('payment/<int:booking_id>/', views.payment, name='payment'),
    path('bookings/<int:booking_id>/receipt/', views.payment_receipt, name='payment_receipt'),
    path('bookings/<int:booking_id>/download-receipt/', views.download_receipt, name='download_receipt'),
    path('delete-booking/<int:booking_id>/', views.delete_booking, name='delete_booking'),
    path('delete-room/<int:room_id>/', views.delete_room, name='delete_room'),
    # Admin patterns
    path('admin/dashboard/', views.dashboard, name='admin_dashboard'),
    path('admin/rooms/', views.manage_rooms, name='manage_rooms'),
    path('admin/rooms/add/', views.add_room, name='add_room'),
    path('admin/rooms/<int:pk>/edit/', views.edit_room, name='edit_room'),
    path('admin/rooms/<int:room_id>/delete/', views.delete_room, name='delete_room'),
    path('admin/rooms/<int:pk>/', views.room_detail, name='room_detail'),
    path('admin/bookings/', views.manage_bookings, name='manage_bookings'),
    path('admin/users/', views.manage_users, name='manage_users'),
    path('admin/users/<int:user_id>/edit/', views.edit_user, name='edit_user'),
    path('admin/users/<int:user_id>/delete/', views.delete_user, name='delete_user'),
    path('admin/equipment/', views.manage_equipment, name='manage_equipment'),
    path('admin/equipment/add/', views.add_equipment, name='add_equipment'),
    path('admin/equipment/<int:equipment_id>/edit/', views.edit_equipment, name='edit_equipment'),
    path('admin/equipment/<int:equipment_id>/delete/', views.delete_equipment, name='delete_equipment'),
    path('admin/equipment/<int:equipment_id>/', views.equipment_detail, name='equipment_detail'),
    path('admin/notifications/', views.manage_notifications, name='manage_notifications'),
    path('admin/notifications/add/', views.add_notification, name='add_notification'),
    path('admin/notifications/<int:notification_id>/edit/', views.edit_notification, name='edit_notification'),
    path('admin/notifications/<int:notification_id>/delete/', views.delete_notification, name='delete_notification'),
    path('admin/notifications/<int:notification_id>/', views.notification_detail, name='notification_detail'),
    path('admin/payments/', views.manage_payments, name='manage_payments'),
    path('admin/payments/<int:payment_id>/', views.payment_detail, name='payment_detail'),
    path('admin/reports/', views.reports, name='reports'),
    path('admin/settings/', views.admin_settings, name='admin_settings'),
    path('admin/download-users/', views.download_users_list, name='download_users_list'),
    path('admin/download-bookings/', views.download_bookings_list, name='download_bookings_list'),
    path('admin/download-rooms/', views.download_rooms_list, name='download_rooms_list'),
    path('bookings/<int:booking_id>/edit/', views.edit_booking, name='edit_booking'),
]
